version: '3.2'
services:
  vaultwarden_dropbox_backup:
    image: jackyaz/vaultwarden_dropbox_backup:latest
    restart: always
    volumes:
      - /path/to/bwdata:/data 
      - /path/to/config:/config
    environment:
      - BACKUP_ENCRYPTION_KEY=xxxyyyzzz
      - CRON="0 1 * * *"
      - TZ=Europe/London #set local timezone using TZ database name standard as seen - https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html
      - DELETE_AFTER=30
