version: '3.2'
services:
  vaultwarden_dropbox_backup:
    image: jackyaz/vaultwarden_dropbox_backup:latest
    restart: always
    volumes:
      - ./bwdata:/data 
      - ./config:/config
    environment:
      - BACKUP_ENCRYPTION_KEY=xxx
      #- DELETE_AFTER=10
      #- TZ=Europe/London #set local timezone using TZ database name standard as seen - https://manpages.ubuntu.com/manpages/bionic/man3/DateTime::TimeZone::Catalog.3pm.html
